### ISSUE TITLE
The .sh file does not work

### ISSUE THREAD

**Issue by QuestionLife** [grapeot/AnimeHeadDetector#3] opened 2021-02-02 10:08 UTC
flashes a command error then exits the shell

**Comment by QuestionLife** [comment] 2021-02-02 21:07
https://lab.grapeot.me/head.weights

404 Error Not Found

**Comment by AnyKeyer** [comment] 2021-02-04 07:40
Duplicate of #2

**Comment by grapeot** [comment] 2023-01-16 23:56
Sorry for the late reply. Somehow github unwatched myself... I just fixed the download link. It's still https://lab.grapeot.me/head.weights.

**Closed as completed by grapeot** 2023-01-16 23:56 UTC
